services:
  megabot: 
    image: botmega
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
    volumes:
      - ./:/app
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - "8000:8000"
    env_file:  ".env"
    command: python3 /app/megabot.py
